version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 85:80
    deploy:
      labels:
        - "traefik.port=80"
        - "traefik.docker.network=traefik"
        - "traefik.frontend.rule=Host:abeherbert.com" 
    environment:
    WORDPRESS_DB_PASSWORD: example

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
