version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 85:80
    deploy:
      labels:
        - "traefik.port=80"
        - "traefik.docker.network=traefik"
        - "traefik.frontend.rule=Host:abeherbert.com"
    environment:
      WORDPRESS_DB_PASSWORD: example
      WORDPRESS_DB_HOST: localhost:3306

  mysql:
    image: mysql:8.0.3
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example

networks:
  traefik:
    external: true
  webgateway:
    external: true
